using Nahmadov.DapperForge.Core.Modeling.Builders;
using Nahmadov.DapperForge.Core.Context.Options;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

public partial class ComplexIncludeTests
{
    #region Test Models - 4 Level Hierarchy

    public class Level1Entity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public Level2Entity? Level2 { get; set; }
    }

    public class Level2Entity
    {
        public int Id { get; set; }
        public int Level1Id { get; set; }
        public string Value { get; set; } = string.Empty;
        public Level3Entity? Level3 { get; set; }
    }

    public class Level3Entity
    {
        public int Id { get; set; }
        public int Level2Id { get; set; }
        public string Data { get; set; } = string.Empty;
        public Level4Entity? Level4 { get; set; }
    }

    public class Level4Entity
    {
        public int Id { get; set; }
        public int Level3Id { get; set; }
        public string Info { get; set; } = string.Empty;
    }

    #endregion

    #region Test Models - Multi-Branch Hierarchy

    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public List<Department> Departments { get; set; } = new();
        public Address? Address { get; set; }
    }

    public class Department
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; } = string.Empty;
        public List<Employee> Employees { get; set; } = new();
    }

    public class Employee
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string Name { get; set; } = string.Empty;
        public List<Project> Projects { get; set; } = new();
    }

    public class Project
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Title { get; set; } = string.Empty;
    }

    public class Address
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Street { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
    }

    #endregion

    #region Test Context

    public class TestContext : DapperDbContext
    {
        public DapperSet<Level1Entity> Level1s => Set<Level1Entity>();
        public DapperSet<Level2Entity> Level2s => Set<Level2Entity>();
        public DapperSet<Level3Entity> Level3s => Set<Level3Entity>();
        public DapperSet<Level4Entity> Level4s => Set<Level4Entity>();
        public DapperSet<Company> Companies => Set<Company>();
        public DapperSet<Department> Departments => Set<Department>();
        public DapperSet<Employee> Employees => Set<Employee>();
        public DapperSet<Project> Projects => Set<Project>();
        public DapperSet<Address> Addresses => Set<Address>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            // 4-level chain
            modelBuilder.Entity<Level1Entity>(b =>
            {
                b.ToTable("Level1");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasOne(e => e.Level2).WithForeignKey<Level2Entity>(e => e.Level1Id);
            });

            modelBuilder.Entity<Level2Entity>(b =>
            {
                b.ToTable("Level2");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasOne(e => e.Level3).WithForeignKey<Level3Entity>(e => e.Level2Id);
            });

            modelBuilder.Entity<Level3Entity>(b =>
            {
                b.ToTable("Level3");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasOne(e => e.Level4).WithForeignKey<Level4Entity>(e => e.Level3Id);
            });

            modelBuilder.Entity<Level4Entity>(b =>
            {
                b.ToTable("Level4");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            // Multi-branch hierarchy
            modelBuilder.Entity<Company>(b =>
            {
                b.ToTable("Companies");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasMany(e => e.Departments).WithForeignKey(d => d.CompanyId);
                // b.HasOne(e => e.Address).WithForeignKey<Address>(a => a.CompanyId);
            });

            modelBuilder.Entity<Department>(b =>
            {
                b.ToTable("Departments");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasMany(e => e.Employees).WithForeignKey(e => e.DepartmentId);
            });

            modelBuilder.Entity<Employee>(b =>
            {
                b.ToTable("Employees");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasMany(e => e.Projects).WithForeignKey(p => p.EmployeeId);
            });

            modelBuilder.Entity<Project>(b =>
            {
                b.ToTable("Projects");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<Address>(b =>
            {
                b.ToTable("Addresses");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }
}
