using Nahmadov.DapperForge.Core.Modeling.Builders;
using Nahmadov.DapperForge.Core.Context.Options;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.Core.Modeling.Mapping;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;
using Xunit;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

/// <summary>
/// Tests for complex Include operations: 4+ level chains, multiple branches, split vs single query
/// </summary>
public class ComplexIncludeTests
{
    #region Test Models - 4 Level Hierarchy

    public class Level1Entity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public Level2Entity? Level2 { get; set; }
    }

    public class Level2Entity
    {
        public int Id { get; set; }
        public int Level1Id { get; set; }
        public string Value { get; set; } = string.Empty;
        public Level3Entity? Level3 { get; set; }
    }

    public class Level3Entity
    {
        public int Id { get; set; }
        public int Level2Id { get; set; }
        public string Data { get; set; } = string.Empty;
        public Level4Entity? Level4 { get; set; }
    }

    public class Level4Entity
    {
        public int Id { get; set; }
        public int Level3Id { get; set; }
        public string Info { get; set; } = string.Empty;
    }

    #endregion

    #region Test Models - Multi-Branch Hierarchy

    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public List<Department> Departments { get; set; } = new();
        public Address? Address { get; set; }
    }

    public class Department
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; } = string.Empty;
        public List<Employee> Employees { get; set; } = new();
    }

    public class Employee
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string Name { get; set; } = string.Empty;
        public List<Project> Projects { get; set; } = new();
    }

    public class Project
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string Title { get; set; } = string.Empty;
    }

    public class Address
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Street { get; set; } = string.Empty;
        public string City { get; set; } = string.Empty;
    }

    #endregion

    #region Test Context

    public class TestContext : DapperDbContext
    {
        public DapperSet<Level1Entity> Level1s => Set<Level1Entity>();
        public DapperSet<Level2Entity> Level2s => Set<Level2Entity>();
        public DapperSet<Level3Entity> Level3s => Set<Level3Entity>();
        public DapperSet<Level4Entity> Level4s => Set<Level4Entity>();
        public DapperSet<Company> Companies => Set<Company>();
        public DapperSet<Department> Departments => Set<Department>();
        public DapperSet<Employee> Employees => Set<Employee>();
        public DapperSet<Project> Projects => Set<Project>();
        public DapperSet<Address> Addresses => Set<Address>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            // 4-level chain
            modelBuilder.Entity<Level1Entity>(b =>
            {
                b.ToTable("Level1");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasOne(e => e.Level2).WithForeignKey<Level2Entity>(e => e.Level1Id);
            });

            modelBuilder.Entity<Level2Entity>(b =>
            {
                b.ToTable("Level2");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasOne(e => e.Level3).WithForeignKey<Level3Entity>(e => e.Level2Id);
            });

            modelBuilder.Entity<Level3Entity>(b =>
            {
                b.ToTable("Level3");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasOne(e => e.Level4).WithForeignKey<Level4Entity>(e => e.Level3Id);
            });

            modelBuilder.Entity<Level4Entity>(b =>
            {
                b.ToTable("Level4");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            // Multi-branch hierarchy
            modelBuilder.Entity<Company>(b =>
            {
                b.ToTable("Companies");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasMany(e => e.Departments).WithForeignKey(d => d.CompanyId);
                // b.HasOne(e => e.Address).WithForeignKey<Address>(a => a.CompanyId);
            });

            modelBuilder.Entity<Department>(b =>
            {
                b.ToTable("Departments");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasMany(e => e.Employees).WithForeignKey(e => e.DepartmentId);
            });

            modelBuilder.Entity<Employee>(b =>
            {
                b.ToTable("Employees");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasMany(e => e.Projects).WithForeignKey(p => p.EmployeeId);
            });

            modelBuilder.Entity<Project>(b =>
            {
                b.ToTable("Projects");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<Address>(b =>
            {
                b.ToTable("Addresses");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }

    #region 4-Level Include Chain Tests

    [Fact]
    public async Task Include_4LevelChain_LoadsAllLevels()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var level4 = new Level4Entity { Id = 4, Level3Id = 3, Info = "Level4Info" };
        var level3 = new Level3Entity { Id = 3, Level2Id = 2, Data = "Level3Data", Level4 = level4 };
        var level2 = new Level2Entity { Id = 2, Level1Id = 1, Value = "Level2Value", Level3 = level3 };
        var level1 = new Level1Entity { Id = 1, Name = "Level1Name", Level2 = level2 };

        conn.SetupQuery(new[] { level1 });
        conn.SetupSplitQuery(new[] { level2 });
        conn.SetupSplitQuery(new[] { level3 });
        conn.SetupSplitQuery(new[] { level4 });

        // Act
        var result = await ctx.Level1s.Query()
            .Include(l1 => l1.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l2 => l2.Level3!)
                .ThenInclude<Level3Entity, Level4Entity>(l3 => l3.Level4!)
            .AsSplitQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(result);
        Assert.Equal("Level1Name", result.Name);
        Assert.NotNull(result.Level2);
        Assert.Equal("Level2Value", result.Level2.Value);
        Assert.NotNull(result.Level2.Level3);
        Assert.Equal("Level3Data", result.Level2.Level3.Data);
        Assert.NotNull(result.Level2.Level3.Level4);
        Assert.Equal("Level4Info", result.Level2.Level3.Level4.Info);
    }

    [Fact]
    public async Task Include_4LevelChain_SingleQuery_LoadsCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var level4 = new Level4Entity { Id = 4, Level3Id = 3, Info = "Level4Info" };
        var level3 = new Level3Entity { Id = 3, Level2Id = 2, Data = "Level3Data", Level4 = level4 };
        var level2 = new Level2Entity { Id = 2, Level1Id = 1, Value = "Level2Value", Level3 = level3 };
        var level1 = new Level1Entity { Id = 1, Name = "Level1Name", Level2 = level2 };

        conn.SetupQuery(new[] { level1 });

        // Act
        var result = await ctx.Level1s.Query()
            .Include(l1 => l1.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l2 => l2.Level3!)
                .ThenInclude<Level3Entity, Level4Entity>(l3 => l3.Level4!)
            .AsSingleQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(result);
        Assert.NotNull(result.Level2);
        Assert.NotNull(result.Level2.Level3);
        Assert.NotNull(result.Level2.Level3.Level4);
    }

    [Fact]
    public async Task Include_4LevelChain_MultipleRootEntities()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var entities = new[]
        {
            new Level1Entity
            {
                Id = 1,
                Name = "First",
                Level2 = new Level2Entity
                {
                    Id = 10,
                    Level1Id = 1,
                    Value = "Val10",
                    Level3 = new Level3Entity
                    {
                        Id = 100,
                        Level2Id = 10,
                        Data = "Data100",
                        Level4 = new Level4Entity { Id = 1000, Level3Id = 100, Info = "Info1000" }
                    }
                }
            },
            new Level1Entity
            {
                Id = 2,
                Name = "Second",
                Level2 = new Level2Entity
                {
                    Id = 20,
                    Level1Id = 2,
                    Value = "Val20",
                    Level3 = new Level3Entity
                    {
                        Id = 200,
                        Level2Id = 20,
                        Data = "Data200",
                        Level4 = new Level4Entity { Id = 2000, Level3Id = 200, Info = "Info2000" }
                    }
                }
            }
        };

        conn.SetupQuery(entities);
        conn.SetupSplitQuery(entities.Select(e => e.Level2!).ToArray());
        conn.SetupSplitQuery(entities.Select(e => e.Level2!.Level3!).ToArray());
        conn.SetupSplitQuery(entities.Select(e => e.Level2!.Level3!.Level4!).ToArray());

        // Act
        var result = (await ctx.Level1s.Query()
            .Include(l1 => l1.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l2 => l2.Level3!)
                .ThenInclude<Level3Entity, Level4Entity>(l3 => l3.Level4!)
            .AsSplitQuery()
            .ToListAsync()).ToList();

        // Assert
        Assert.Equal(2, result.Count);
        Assert.All(result, entity =>
        {
            Assert.NotNull(entity.Level2);
            Assert.NotNull(entity.Level2.Level3);
            Assert.NotNull(entity.Level2.Level3.Level4);
        });
    }

    #endregion

    #region Multi-Branch Include Tests

    [Fact]
    public async Task Include_MultipleBranches_LoadsCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var company = new Company
        {
            Id = 1,
            Name = "TechCorp",
            Departments = new List<Department>
            {
                new Department { Id = 10, CompanyId = 1, Name = "Engineering" },
                new Department { Id = 20, CompanyId = 1, Name = "Sales" }
            },
            Address = new Address { Id = 100, CompanyId = 1, Street = "123 Main St", City = "TechCity" }
        };

        conn.SetupQuery(new[] { company });
        conn.SetupSplitQuery(company.Departments.ToArray());
        conn.SetupSplitQuery(new[] { company.Address });

        // Act
        var result = await ctx.Companies.Query()
            .Include(c => c.Departments)
            .Include(c => c.Address)
            .AsSplitQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(result);
        Assert.Equal(2, result.Departments.Count);
        Assert.NotNull(result.Address);
        Assert.Equal("123 Main St", result.Address.Street);
    }

    [Fact]
    public async Task Include_4LevelMultiBranch_CompanyToProjects()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var projects = new[]
        {
            new Project { Id = 1, EmployeeId = 100, Title = "Project Alpha" },
            new Project { Id = 2, EmployeeId = 100, Title = "Project Beta" }
        };

        var employees = new[]
        {
            new Employee
            {
                Id = 100,
                DepartmentId = 10,
                Name = "John Doe",
                Projects = projects.ToList()
            }
        };

        var departments = new[]
        {
            new Department
            {
                Id = 10,
                CompanyId = 1,
                Name = "Engineering",
                Employees = employees.ToList()
            }
        };

        var company = new Company
        {
            Id = 1,
            Name = "TechCorp",
            Departments = departments.ToList()
        };

        conn.SetupQuery(new[] { company });
        conn.SetupSplitQuery(departments);
        conn.SetupSplitQuery(employees);
        conn.SetupSplitQuery(projects);

        // Act
        var result = await ctx.Companies.Query()
            .Include(c => c.Departments)
                .ThenInclude<Department, IEnumerable<Employee>>(d => d.Employees)
                .ThenInclude<Employee, IEnumerable<Project>>(e => e.Projects)
            .AsSplitQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(result);
        Assert.Single(result.Departments);
        Assert.Single(result.Departments[0].Employees);
        Assert.Equal(2, result.Departments[0].Employees[0].Projects.Count);
    }

    #endregion

    #region Performance Comparison Tests

    [Fact]
    public async Task Include_SplitQuery_vs_SingleQuery_BothWork()
    {
        // Arrange
        var (ctx1, conn1) = CreateContext();
        var (ctx2, conn2) = CreateContext();

        var level1 = new Level1Entity
        {
            Id = 1,
            Name = "Test",
            Level2 = new Level2Entity
            {
                Id = 2,
                Level1Id = 1,
                Value = "Val",
                Level3 = new Level3Entity
                {
                    Id = 3,
                    Level2Id = 2,
                    Data = "Data",
                    Level4 = new Level4Entity { Id = 4, Level3Id = 3, Info = "Info" }
                }
            }
        };

        conn1.SetupQuery(new[] { level1 });
        conn1.SetupSplitQuery(new[] { level1.Level2 });
        conn1.SetupSplitQuery(new[] { level1.Level2.Level3 });
        conn1.SetupSplitQuery(new[] { level1.Level2.Level3.Level4 });

        conn2.SetupQuery(new[] { level1 });

        // Act
        var resultSplit = await ctx1.Level1s.Query()
            .Include(l => l.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l => l.Level3!)
                .ThenInclude<Level3Entity, Level4Entity>(l => l.Level4!)
            .AsSplitQuery()
            .FirstOrDefaultAsync();

        var resultSingle = await ctx2.Level1s.Query()
            .Include(l => l.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l => l.Level3!)
                .ThenInclude<Level3Entity, Level4Entity>(l => l.Level4!)
            .AsSingleQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(resultSplit);
        Assert.NotNull(resultSplit.Level2?.Level3?.Level4);

        Assert.NotNull(resultSingle);
        Assert.NotNull(resultSingle.Level2?.Level3?.Level4);
    }

    #endregion

    #region Edge Cases in Deep Includes

    [Fact]
    public async Task Include_4Levels_WithNullAtLevel2()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var level1 = new Level1Entity { Id = 1, Name = "Root", Level2 = null };
        conn.SetupQuery(new[] { level1 });
        conn.SetupSplitQuery(Array.Empty<Level2Entity>());

        // Act
        var result = await ctx.Level1s.Query()
            .Include(l => l.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l => l.Level3!)
            .AsSplitQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(result);
        Assert.Null(result.Level2);
    }

    [Fact]
    public async Task Include_DeepChain_WithWhere_FiltersCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var entities = new[]
        {
            new Level1Entity
            {
                Id = 1,
                Name = "Active",
                Level2 = new Level2Entity
                {
                    Id = 10,
                    Level1Id = 1,
                    Value = "ActiveValue",
                    Level3 = new Level3Entity { Id = 100, Level2Id = 10, Data = "Data" }
                }
            }
        };

        conn.SetupQuery(entities);
        conn.SetupSplitQuery(entities.Select(e => e.Level2!).ToArray());
        conn.SetupSplitQuery(entities.Select(e => e.Level2!.Level3!).ToArray());

        // Act
        var result = await ctx.Level1s.Query()
            .Where(l => l.Name == "Active")
            .Include(l => l.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l => l.Level3!)
            .AsSplitQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(result);
        Assert.Equal("Active", result.Name);
        Assert.NotNull(result.Level2);
        Assert.NotNull(result.Level2.Level3);
    }

    [Fact]
    public async Task Include_DeepChain_WithOrderBy_MaintainsOrder()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var entities = new[]
        {
            new Level1Entity { Id = 3, Name = "Third", Level2 = new Level2Entity { Id = 30, Level1Id = 3, Value = "Val3" } },
            new Level1Entity { Id = 1, Name = "First", Level2 = new Level2Entity { Id = 10, Level1Id = 1, Value = "Val1" } },
            new Level1Entity { Id = 2, Name = "Second", Level2 = new Level2Entity { Id = 20, Level1Id = 2, Value = "Val2" } }
        };

        var orderedEntities = entities.OrderBy(e => e.Id).ToArray();
        conn.SetupQuery(orderedEntities);
        conn.SetupSplitQuery(orderedEntities.Select(e => e.Level2!).ToArray());

        // Act
        var result = (await ctx.Level1s.Query()
            .OrderBy(l => l.Id)
            .Include(l => l.Level2)
            .AsSplitQuery()
            .ToListAsync()).ToList();

        // Assert
        Assert.Equal(3, result.Count);
        Assert.Equal(1, result[0].Id);
        Assert.Equal(2, result[1].Id);
        Assert.Equal(3, result[2].Id);
        Assert.All(result, r => Assert.NotNull(r.Level2));
    }

    #endregion

    #region Identity Resolution in Deep Includes

    [Fact]
    public async Task Include_DeepChain_AsNoIdentityResolution_AllowsDuplicates()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var sharedLevel4 = new Level4Entity { Id = 4, Level3Id = 3, Info = "Shared" };
        var entities = new[]
        {
            new Level1Entity
            {
                Id = 1,
                Name = "First",
                Level2 = new Level2Entity
                {
                    Id = 2,
                    Level1Id = 1,
                    Value = "Val",
                    Level3 = new Level3Entity { Id = 3, Level2Id = 2, Data = "Data", Level4 = sharedLevel4 }
                }
            }
        };

        conn.SetupQuery(entities);
        conn.SetupSplitQuery(entities.Select(e => e.Level2!).ToArray());
        conn.SetupSplitQuery(entities.Select(e => e.Level2!.Level3!).ToArray());
        conn.SetupSplitQuery(new[] { sharedLevel4 });

        // Act
        var result = await ctx.Level1s.Query()
            .Include(l => l.Level2)
                .ThenInclude<Level2Entity, Level3Entity>(l => l.Level3!)
                .ThenInclude<Level3Entity, Level4Entity>(l => l.Level4!)
            .AsNoIdentityResolution()
            .AsSplitQuery()
            .FirstOrDefaultAsync();

        // Assert
        Assert.NotNull(result);
        Assert.NotNull(result.Level2?.Level3?.Level4);
    }

    #endregion
}



