using System.Collections.Concurrent;
using System.Data;
using Nahmadov.DapperForge.Core.Builders;
using Nahmadov.DapperForge.Core.Common;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.Core.Mapping;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;
using Xunit;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

/// <summary>
/// Tests for concurrent operations: thread-safety, parallel queries, connection pooling
/// </summary>
public class ConcurrentOperationsTests
{
    #region Test Models

    public class TestEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; }
    }

    public class TestContext : DapperDbContext
    {
        public DapperSet<TestEntity> Entities => Set<TestEntity>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TestEntity>(b =>
            {
                b.ToTable("TestEntities");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }

    #region Concurrent Query Tests

    [Fact]
    public async Task ConcurrentQueries_MultipleTasks_ExecuteSuccessfully()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var testData = Enumerable.Range(1, 100)
            .Select(i => new TestEntity { Id = i, Name = $"Entity{i}" })
            .ToArray();
        conn.SetupQuery(testData);

        // Act - Execute 10 concurrent queries
        var tasks = Enumerable.Range(0, 10)
            .Select(_ => ctx.Entities.Query().ToListAsync())
            .ToArray();

        var results = await Task.WhenAll(tasks);

        // Assert
        Assert.All(results, result => Assert.Equal(100, result.Count()));
    }

    [Fact]
    public async Task ConcurrentWhere_SameExpression_ReusesCachedCompilation()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var testData = new[] { new TestEntity { Id = 1, Name = "Test" } };
        conn.SetupQuery(testData);

        // Act - Execute 20 concurrent queries with same Where predicate
        var tasks = Enumerable.Range(0, 20)
            .Select(_ => ctx.Entities.Query().Where(e => e.Id == 1).ToListAsync())
            .ToArray();

        var results = await Task.WhenAll(tasks);

        // Assert - All queries should succeed
        Assert.All(results, result => Assert.Single(result));
    }

    [Fact]
    public async Task ConcurrentInsert_MultipleThreads_ExecutesWithoutErrors()
    {
        // Arrange
        var connectionCount = 0;
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () =>
            {
                Interlocked.Increment(ref connectionCount);
                var conn = new FakeDbConnection();
                conn.SetupExecute(1);
                return conn;
            },
            Dialect = SqlServerDialect.Instance
        };

        // Act - Insert from 10 concurrent threads
        var tasks = Enumerable.Range(1, 10)
            .Select(i => Task.Run(async () =>
            {
                var ctx = new TestContext(options);
                var entity = new TestEntity { Id = i, Name = $"Concurrent{i}" };
                return await ctx.Entities.InsertAsync(entity);
            }))
            .ToArray();

        var results = await Task.WhenAll(tasks);

        // Assert
        Assert.All(results, result => Assert.Equal(1, result));
        Assert.Equal(10, connectionCount); // Each task should get its own connection
    }

    [Fact]
    public async Task ConcurrentUpdate_DifferentEntities_ExecutesSuccessfully()
    {
        // Arrange
        var connectionCount = 0;
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () =>
            {
                Interlocked.Increment(ref connectionCount);
                var conn = new FakeDbConnection();
                conn.SetupExecute(1);
                return conn;
            },
            Dialect = SqlServerDialect.Instance
        };

        // Act - Update from 5 concurrent threads
        var tasks = Enumerable.Range(1, 5)
            .Select(i => Task.Run(async () =>
            {
                var ctx = new TestContext(options);
                var entity = new TestEntity { Id = i, Name = $"Updated{i}" };
                return await ctx.Entities.UpdateAsync(entity);
            }))
            .ToArray();

        var results = await Task.WhenAll(tasks);

        // Assert
        Assert.All(results, result => Assert.Equal(1, result));
        Assert.Equal(5, connectionCount);
    }

    #endregion

    #region Connection Pool Simulation Tests

    [Fact]
    public async Task SharedConnectionFactory_ConcurrentAccess_HandlesCorrectly()
    {
        // Arrange - Simulate connection pooling
        var connectionPool = new ConcurrentBag<FakeDbConnection>();
        var createCount = 0;

        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () =>
            {
                if (connectionPool.TryTake(out var conn))
                {
                    return conn;
                }
                Interlocked.Increment(ref createCount);
                var newConn = new FakeDbConnection();
                newConn.SetupQuery(new[] { new TestEntity { Id = 1, Name = "Test" } });
                return newConn;
            },
            Dialect = SqlServerDialect.Instance
        };

        var ctx = new TestContext(options);

        // Act - Execute 50 concurrent queries
        var tasks = Enumerable.Range(0, 50)
            .Select(_ => Task.Run(async () =>
            {
                var result = await ctx.Entities.FindAsync(1);
                return result;
            }))
            .ToArray();

        var results = await Task.WhenAll(tasks);

        // Assert
        Assert.All(results, result => Assert.NotNull(result));
        // Should create connections as needed
        Assert.True(createCount > 0);
    }

    #endregion

    #region Expression Compilation Cache Tests

    [Fact]
    public async Task ExpressionCache_ConcurrentAccess_ThreadSafe()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        conn.SetupQuery(Array.Empty<TestEntity>());

        // Act - Execute many concurrent queries with different predicates
        var tasks = Enumerable.Range(1, 100)
            .Select(i => Task.Run(async () =>
            {
                // Alternate between different predicates
                if (i % 2 == 0)
                    return await ctx.Entities.Query().Where(e => e.Id == i).ToListAsync();
                else
                    return await ctx.Entities.Query().Where(e => e.Name == $"Entity{i}").ToListAsync();
            }))
            .ToArray();

        // Assert - Should complete without exceptions
        var results = await Task.WhenAll(tasks);
        Assert.Equal(100, results.Length);
    }

    [Fact]
    public async Task ConcurrentOrderBy_DifferentProperties_ExecutesCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var testData = Enumerable.Range(1, 50)
            .Select(i => new TestEntity { Id = i, Name = $"Entity{i}", CreatedAt = DateTime.Now.AddDays(-i) })
            .ToArray();
        conn.SetupQuery(testData);
        _ = ctx.Entities; // warm up model build before concurrent access

        // Act - Concurrent queries with different OrderBy
        var tasks = new List<Task<IEnumerable<TestEntity>>>
        {
            Task.Run(() => ctx.Entities.Query().OrderBy(e => e.Id).ToListAsync()),
            Task.Run(() => ctx.Entities.Query().OrderBy(e => e.Name).ToListAsync()),
            Task.Run(() => ctx.Entities.Query().OrderBy(e => e.CreatedAt).ToListAsync()),
            Task.Run(() => ctx.Entities.Query().OrderByDescending(e => e.Id).ToListAsync()),
            Task.Run(() => ctx.Entities.Query().OrderByDescending(e => e.Name).ToListAsync())
        };

        var results = await Task.WhenAll(tasks);

        // Assert
        Assert.All(results, result => Assert.Equal(50, result.Count()));
    }

    #endregion

    #region Stress Tests

    [Fact]
    public async Task HighConcurrency_100Tasks_CompletesSuccessfully()
    {
        // Arrange
        var connectionCount = 0;
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () =>
            {
                Interlocked.Increment(ref connectionCount);
                var conn = new FakeDbConnection();
                conn.SetupQuery(new[] { new TestEntity { Id = 1, Name = "Test" } });
                conn.SetupExecute(1);
                return conn;
            },
            Dialect = SqlServerDialect.Instance
        };

        // Act - Mix of read and write operations
        var tasks = new List<Task>();

        // 50 reads
        for (int i = 0; i < 50; i++)
        {
            tasks.Add(Task.Run(async () =>
            {
                var ctx = new TestContext(options);
                await ctx.Entities.Query().ToListAsync();
            }));
        }

        // 30 inserts
        for (int i = 0; i < 30; i++)
        {
            var id = i;
            tasks.Add(Task.Run(async () =>
            {
                var ctx = new TestContext(options);
                await ctx.Entities.InsertAsync(new TestEntity { Id = id, Name = $"Insert{id}" });
            }));
        }

        // 20 updates
        for (int i = 0; i < 20; i++)
        {
            var id = i;
            tasks.Add(Task.Run(async () =>
            {
                var ctx = new TestContext(options);
                await ctx.Entities.UpdateAsync(new TestEntity { Id = id, Name = $"Update{id}" });
            }));
        }

        // Assert - All operations complete without exceptions
        await Task.WhenAll(tasks);
        Assert.True(connectionCount > 0);
    }

    [Fact]
    public async Task RapidFireQueries_SameContext_ExecutesSequentially()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        conn.SetupQuery(new[] { new TestEntity { Id = 1, Name = "Test" } });

        // Act - Rapid sequential queries on same context
        var results = new List<TestEntity?>();
        for (int i = 0; i < 100; i++)
        {
            var result = await ctx.Entities.FindAsync(1);
            results.Add(result);
        }

        // Assert
        Assert.Equal(100, results.Count);
        Assert.All(results, r => Assert.NotNull(r));
    }

    #endregion

    #region Race Condition Tests

    [Fact]
    public async Task ConcurrentReadWrite_NoDataCorruption()
    {
        // Arrange
        var sharedData = new ConcurrentBag<TestEntity>();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () =>
            {
                var conn = new FakeDbConnection();
                conn.SetupQuery(sharedData.ToArray());
                conn.SetupExecute(1);
                return conn;
            },
            Dialect = SqlServerDialect.Instance
        };

        // Act - Concurrent reads while data is being "inserted"
        var writeTasks = Enumerable.Range(1, 20)
            .Select(i => Task.Run(async () =>
            {
                var entity = new TestEntity { Id = i, Name = $"Entity{i}" };
                sharedData.Add(entity);
                var ctx = new TestContext(options);
                await ctx.Entities.InsertAsync(entity);
            }));

        var readTasks = Enumerable.Range(0, 30)
            .Select(_ => Task.Run(async () =>
            {
                await Task.Delay(Random.Shared.Next(1, 10)); // Random delay
                var ctx = new TestContext(options);
                return await ctx.Entities.Query().ToListAsync();
            }));

        await Task.WhenAll(writeTasks.Concat(readTasks));

        // Assert - No exceptions thrown
        Assert.True(sharedData.Count >= 20);
    }

    #endregion
}
