using Nahmadov.DapperForge.Core.Modeling.Builders;
using Nahmadov.DapperForge.Core.Context.Options;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.Core.Modeling.Mapping;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;
using Xunit;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

/// <summary>
/// Tests for DateTime and DateTimeOffset handling: UTC, local time, time zones, date comparisons
/// </summary>
public class DateTimeTests
{
    #region Test Models

    public class EventEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTimeOffset Timestamp { get; set; }
        public DateTimeOffset? OptionalTimestamp { get; set; }
    }

    public class DateOnlyEntity
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; } = string.Empty;
    }

    public class TestContext : DapperDbContext
    {
        public DapperSet<EventEntity> Events => Set<EventEntity>();
        public DapperSet<DateOnlyEntity> DateEntities => Set<DateOnlyEntity>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EventEntity>(b =>
            {
                b.ToTable("Events");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<DateOnlyEntity>(b =>
            {
                b.ToTable("DateEntities");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }

    #region DateTime Insert/Update Tests

    [Fact]
    public async Task InsertAsync_WithDateTime_PreservesValue()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var now = new DateTime(2024, 1, 15, 10, 30, 45, DateTimeKind.Utc);
        var entity = new EventEntity
        {
            Id = 1,
            Name = "Test Event",
            CreatedAt = now,
            Timestamp = new DateTimeOffset(now)
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task InsertAsync_WithNullableDateTime_HandlesNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new EventEntity
        {
            Id = 1,
            Name = "Test Event",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = null,
            Timestamp = DateTimeOffset.UtcNow,
            OptionalTimestamp = null
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task UpdateAsync_ChangesDateTime_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var originalTime = new DateTime(2024, 1, 1, 12, 0, 0, DateTimeKind.Utc);
        var updatedTime = new DateTime(2024, 1, 15, 14, 30, 0, DateTimeKind.Utc);

        var entity = new EventEntity
        {
            Id = 1,
            Name = "Test Event",
            CreatedAt = originalTime,
            UpdatedAt = updatedTime,
            Timestamp = DateTimeOffset.UtcNow
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.UpdateAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    #endregion

    #region DateTime Query Tests

    [Fact]
    public async Task Where_DateTimeEquals_FindsMatch()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var targetDate = new DateTime(2024, 1, 15, 10, 30, 45, DateTimeKind.Utc);
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "Event1", CreatedAt = targetDate, Timestamp = DateTimeOffset.UtcNow },
            new EventEntity { Id = 2, Name = "Event2", CreatedAt = DateTime.UtcNow, Timestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(new[] { events[0] });

        // Act
        var result = await ctx.Events.Query().Where(e => e.CreatedAt == targetDate).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Equal(targetDate, result.First().CreatedAt);
    }

    [Fact]
    public async Task Where_DateTimeGreaterThan_FiltersCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var cutoffDate = new DateTime(2024, 1, 10, 0, 0, 0, DateTimeKind.Utc);
        var futureEvents = new[]
        {
            new EventEntity { Id = 1, Name = "Future1", CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow },
            new EventEntity { Id = 2, Name = "Future2", CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(futureEvents);

        // Act
        var result = await ctx.Events.Query().Where(e => e.CreatedAt > cutoffDate).ToListAsync();

        // Assert
        Assert.Equal(2, result.Count());
        Assert.All(result, e => Assert.True(e.CreatedAt > cutoffDate));
    }

    [Fact]
    public async Task Where_DateTimeLessThan_FiltersCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var cutoffDate = new DateTime(2024, 1, 10, 0, 0, 0, DateTimeKind.Utc);
        var pastEvents = new[]
        {
            new EventEntity { Id = 1, Name = "Past1", CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(pastEvents);

        // Act
        var result = await ctx.Events.Query().Where(e => e.CreatedAt < cutoffDate).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.True(result.First().CreatedAt < cutoffDate);
    }

    [Fact]
    public async Task Where_DateTimeBetween_FindsRange()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var startDate = new DateTime(2024, 1, 10, 0, 0, 0, DateTimeKind.Utc);
        var endDate = new DateTime(2024, 1, 20, 0, 0, 0, DateTimeKind.Utc);
        var eventsInRange = new[]
        {
            new EventEntity { Id = 1, Name = "InRange", CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(eventsInRange);

        // Act
        var result = await ctx.Events.Query()
            .Where(e => e.CreatedAt >= startDate && e.CreatedAt <= endDate)
            .ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.InRange(result.First().CreatedAt, startDate, endDate);
    }

    #endregion

    #region DateTimeOffset Tests

    [Fact]
    public async Task InsertAsync_WithDateTimeOffset_PreservesTimezone()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var offset = TimeSpan.FromHours(5);
        var timestamp = new DateTimeOffset(2024, 1, 15, 10, 30, 45, offset);

        var entity = new EventEntity
        {
            Id = 1,
            Name = "Test Event",
            CreatedAt = DateTime.UtcNow,
            Timestamp = timestamp,
            OptionalTimestamp = timestamp.AddHours(1)
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task Query_WithDateTimeOffset_ComparesCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var targetOffset = new DateTimeOffset(2024, 1, 15, 10, 0, 0, TimeSpan.Zero);
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "Event1", CreatedAt = DateTime.UtcNow, Timestamp = targetOffset }
        };
        conn.SetupQuery(events);

        // Act
        var result = await ctx.Events.Query().Where(e => e.Timestamp == targetOffset).ToListAsync();

        // Assert
        Assert.Single(result);
    }

    [Fact]
    public async Task Query_NullableDateTimeOffset_HandlesNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "WithNull", CreatedAt = DateTime.UtcNow, Timestamp = DateTimeOffset.UtcNow, OptionalTimestamp = null },
            new EventEntity { Id = 2, Name = "WithValue", CreatedAt = DateTime.UtcNow, Timestamp = DateTimeOffset.UtcNow, OptionalTimestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(new[] { events[0] });

        // Act
        var result = await ctx.Events.Query().Where(e => e.OptionalTimestamp == null).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Null(result.First().OptionalTimestamp);
    }

    #endregion

    #region DateTime.UtcNow and DateTime.Now Tests

    [Fact]
    public async Task InsertAsync_WithUtcNow_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new EventEntity
        {
            Id = 1,
            Name = "Test Event",
            CreatedAt = DateTime.UtcNow,
            Timestamp = DateTimeOffset.UtcNow
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
        Assert.Equal(DateTimeKind.Utc, entity.CreatedAt.Kind);
    }

    [Fact]
    public async Task InsertAsync_WithLocalNow_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new EventEntity
        {
            Id = 1,
            Name = "Test Event",
            CreatedAt = DateTime.Now,
            Timestamp = DateTimeOffset.Now
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    #endregion

    #region Date-Only Queries

    [Fact]
    public async Task Where_DateProperty_ComparesDateOnly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var targetDate = new DateTime(2024, 1, 15).Date;
        var entities = new[]
        {
            new DateOnlyEntity { Id = 1, Date = new DateTime(2024, 1, 15, 10, 30, 0), Description = "Match" },
            new DateOnlyEntity { Id = 2, Date = new DateTime(2024, 1, 16, 10, 30, 0), Description = "NoMatch" }
        };
        conn.SetupQuery(new[] { entities[0] });

        // Act
        var result = await ctx.DateEntities.Query().Where(e => e.Date.Date == targetDate).ToListAsync();

        // Assert
        Assert.Single(result);
    }

    [Fact]
    public async Task OrderBy_DateTime_SortsChronologically()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entities = new[]
        {
            new EventEntity { Id = 3, Name = "Latest", CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow },
            new EventEntity { Id = 1, Name = "Earliest", CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow },
            new EventEntity { Id = 2, Name = "Middle", CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow }
        };
        var sortedEntities = entities.OrderBy(e => e.CreatedAt).ToArray();
        conn.SetupQuery(sortedEntities);

        // Act
        var result = (await ctx.Events.Query().OrderBy(e => e.CreatedAt).ToListAsync()).ToList();

        // Assert
        Assert.Equal(3, result.Count);
        Assert.Equal("Earliest", result[0].Name);
        Assert.Equal("Middle", result[1].Name);
        Assert.Equal("Latest", result[2].Name);
    }

    [Fact]
    public async Task OrderByDescending_DateTime_SortsReverseChronologically()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entities = new[]
        {
            new EventEntity { Id = 1, Name = "Earliest", CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow },
            new EventEntity { Id = 2, Name = "Middle", CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow },
            new EventEntity { Id = 3, Name = "Latest", CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, DateTimeKind.Utc), Timestamp = DateTimeOffset.UtcNow }
        };
        var sortedEntities = entities.OrderByDescending(e => e.CreatedAt).ToArray();
        conn.SetupQuery(sortedEntities);

        // Act
        var result = (await ctx.Events.Query().OrderByDescending(e => e.CreatedAt).ToListAsync()).ToList();

        // Assert
        Assert.Equal(3, result.Count);
        Assert.Equal("Latest", result[0].Name);
        Assert.Equal("Middle", result[1].Name);
        Assert.Equal("Earliest", result[2].Name);
    }

    #endregion

    #region DateTime Edge Cases

    [Fact]
    public async Task InsertAsync_WithMinDateTime_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new EventEntity
        {
            Id = 1,
            Name = "Min Date",
            CreatedAt = DateTime.MinValue,
            Timestamp = DateTimeOffset.MinValue
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task InsertAsync_WithMaxDateTime_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new EventEntity
        {
            Id = 1,
            Name = "Max Date",
            CreatedAt = DateTime.MaxValue,
            Timestamp = DateTimeOffset.MaxValue
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Events.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task Query_WithMinDateTime_FindsMatch()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "MinDate", CreatedAt = DateTime.MinValue, Timestamp = DateTimeOffset.MinValue }
        };
        conn.SetupQuery(events);

        // Act
        var result = await ctx.Events.Query().Where(e => e.CreatedAt == DateTime.MinValue).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Equal(DateTime.MinValue, result.First().CreatedAt);
    }

    [Fact]
    public async Task Query_WithMaxDateTime_FindsMatch()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "MaxDate", CreatedAt = DateTime.MaxValue, Timestamp = DateTimeOffset.MaxValue }
        };
        conn.SetupQuery(events);

        // Act
        var result = await ctx.Events.Query().Where(e => e.CreatedAt == DateTime.MaxValue).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Equal(DateTime.MaxValue, result.First().CreatedAt);
    }

    #endregion

    #region Nullable DateTime Tests

    [Fact]
    public async Task Where_NullableDateTime_IsNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "NeverUpdated", CreatedAt = DateTime.UtcNow, UpdatedAt = null, Timestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(events);

        // Act
        var result = await ctx.Events.Query().Where(e => e.UpdatedAt == null).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Null(result.First().UpdatedAt);
    }

    [Fact]
    public async Task Where_NullableDateTime_IsNotNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "Updated", CreatedAt = DateTime.UtcNow, UpdatedAt = DateTime.UtcNow, Timestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(events);

        // Act
        var result = await ctx.Events.Query().Where(e => e.UpdatedAt != null).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.NotNull(result.First().UpdatedAt);
    }

    #endregion

    #region DateTime Arithmetic Tests

    [Fact]
    public async Task Where_DateTimeAddDays_ComparesCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var baseDate = new DateTime(2024, 1, 10, 0, 0, 0, DateTimeKind.Utc);
        var events = new[]
        {
            new EventEntity { Id = 1, Name = "Event", CreatedAt = baseDate.AddDays(5), Timestamp = DateTimeOffset.UtcNow }
        };
        conn.SetupQuery(events);

        // Act - Find events created exactly 5 days after base date
        var targetDate = baseDate.AddDays(5);
        var result = await ctx.Events.Query().Where(e => e.CreatedAt == targetDate).ToListAsync();

        // Assert
        Assert.Single(result);
    }

    #endregion
}



