using Nahmadov.DapperForge.Core.Modeling.Builders;
using Nahmadov.DapperForge.Core.Context.Options;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

public partial class DateTimeTests
{
    #region Test Models

    public class EventEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public DateTimeOffset Timestamp { get; set; }
        public DateTimeOffset? OptionalTimestamp { get; set; }
    }

    public class DateOnlyEntity
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; } = string.Empty;
    }

    public class TestContext : DapperDbContext
    {
        public DapperSet<EventEntity> Events => Set<EventEntity>();
        public DapperSet<DateOnlyEntity> DateEntities => Set<DateOnlyEntity>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EventEntity>(b =>
            {
                b.ToTable("Events");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<DateOnlyEntity>(b =>
            {
                b.ToTable("DateEntities");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }
}
