using System.Data;
using Nahmadov.DapperForge.Core.Builders;
using Nahmadov.DapperForge.Core.Common;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.Core.Exceptions;
using Nahmadov.DapperForge.Core.Mapping;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;
using Xunit;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

/// <summary>
/// Tests for edge cases: empty keys, zero IDs, Guid.Empty, boundary values
/// </summary>
public class EdgeCaseTests
{
    #region Test Models

    public class IntKeyEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }

    public class GuidKeyEntity
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }

    public class LongKeyEntity
    {
        public long Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }

    public class TestContext : DapperDbContext
    {
        public DapperSet<IntKeyEntity> IntEntities => Set<IntKeyEntity>();
        public DapperSet<GuidKeyEntity> GuidEntities => Set<GuidKeyEntity>();
        public DapperSet<LongKeyEntity> LongEntities => Set<LongKeyEntity>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IntKeyEntity>(b =>
            {
                b.ToTable("IntEntities");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<GuidKeyEntity>(b =>
            {
                b.ToTable("GuidEntities");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<LongKeyEntity>(b =>
            {
                b.ToTable("LongEntities");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }

    #region Empty/Zero Key Tests

    [Fact]
    public async Task FindAsync_ZeroId_ReturnsNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        conn.SetupQuery<IntKeyEntity>(Enumerable.Empty<IntKeyEntity>());

        // Act
        var result = await ctx.IntEntities.FindAsync(0);

        // Assert
        Assert.Null(result);
    }

    [Fact]
    public async Task FindAsync_GuidEmpty_ReturnsNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        conn.SetupQuery<GuidKeyEntity>(Enumerable.Empty<GuidKeyEntity>());

        // Act
        var result = await ctx.GuidEntities.FindAsync(Guid.Empty);

        // Assert
        Assert.Null(result);
    }

    [Fact]
    public async Task InsertAsync_EntityWithZeroId_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new IntKeyEntity { Id = 0, Name = "Test" };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.IntEntities.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task InsertAsync_EntityWithGuidEmpty_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new GuidKeyEntity { Id = Guid.Empty, Name = "Test" };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.GuidEntities.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task UpdateAsync_EntityWithZeroId_ExecutesWithoutError()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new IntKeyEntity { Id = 0, Name = "Updated" };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.IntEntities.UpdateAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task DeleteAsync_EntityWithZeroId_ExecutesWithoutError()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new IntKeyEntity { Id = 0, Name = "ToDelete" };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.IntEntities.DeleteAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task DeleteByIdAsync_ZeroId_ExecutesWithoutError()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        conn.SetupExecute(1);

        // Act
        var result = await ctx.IntEntities.DeleteByIdAsync(0);

        // Assert
        Assert.Equal(1, result);
    }

    #endregion

    #region Boundary Value Tests

    [Fact]
    public async Task FindAsync_MaxIntValue_ReturnsCorrectEntity()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var expectedEntity = new IntKeyEntity { Id = int.MaxValue, Name = "MaxInt" };
        conn.SetupQuery(new[] { expectedEntity });

        // Act
        var result = await ctx.IntEntities.FindAsync(int.MaxValue);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(int.MaxValue, result.Id);
    }

    [Fact]
    public async Task FindAsync_MinIntValue_ReturnsCorrectEntity()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var expectedEntity = new IntKeyEntity { Id = int.MinValue, Name = "MinInt" };
        conn.SetupQuery(new[] { expectedEntity });

        // Act
        var result = await ctx.IntEntities.FindAsync(int.MinValue);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(int.MinValue, result.Id);
    }

    [Fact]
    public async Task FindAsync_MaxLongValue_ReturnsCorrectEntity()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var expectedEntity = new LongKeyEntity { Id = long.MaxValue, Name = "MaxLong" };
        conn.SetupQuery(new[] { expectedEntity });

        // Act
        var result = await ctx.LongEntities.FindAsync(long.MaxValue);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(long.MaxValue, result.Id);
    }

    #endregion

    #region Exception Propagation Tests

    [Fact]
    public async Task InsertAsync_DatabaseException_WrapsInDapperExecutionException()
    {
        // Arrange
        var (ctx, _) = CreateContext();
        var entity = new IntKeyEntity { Id = 1, Name = "Test" };

        // Use a broken connection that throws
        var brokenOptions = new DapperDbContextOptions
        {
            ConnectionFactory = () => throw new InvalidOperationException("Connection failed"),
            Dialect = SqlServerDialect.Instance
        };
        var brokenCtx = new TestContext(brokenOptions);

        // Act & Assert
        await Assert.ThrowsAsync<DapperConnectionException>(async () =>
            await brokenCtx.IntEntities.InsertAsync(entity));
    }

    [Fact]
    public async Task UpdateAsync_NoRowsAffected_ThrowsConcurrencyException()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new IntKeyEntity { Id = 999, Name = "NonExistent" };
        conn.SetupExecute(0); // No rows affected

        // Act & Assert
        await Assert.ThrowsAsync<DapperConcurrencyException>(async () =>
            await ctx.IntEntities.UpdateAsync(entity));
    }

    [Fact]
    public async Task DeleteAsync_NoRowsAffected_ThrowsConcurrencyException()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new IntKeyEntity { Id = 999, Name = "NonExistent" };
        conn.SetupExecute(0); // No rows affected

        // Act & Assert
        await Assert.ThrowsAsync<DapperConcurrencyException>(async () =>
            await ctx.IntEntities.DeleteAsync(entity));
    }

    [Fact]
    public async Task DeleteByIdAsync_NoRowsAffected_ThrowsConcurrencyException()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        conn.SetupExecute(0); // No rows affected

        // Act & Assert
        await Assert.ThrowsAsync<DapperConcurrencyException>(async () =>
            await ctx.IntEntities.DeleteByIdAsync(999));
    }

    #endregion

    #region Negative ID Tests

    [Fact]
    public async Task FindAsync_NegativeId_ReturnsEntity()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var expectedEntity = new IntKeyEntity { Id = -1, Name = "Negative" };
        conn.SetupQuery(new[] { expectedEntity });

        // Act
        var result = await ctx.IntEntities.FindAsync(-1);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(-1, result.Id);
    }

    [Fact]
    public async Task InsertAsync_NegativeId_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var entity = new IntKeyEntity { Id = -100, Name = "NegativeId" };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.IntEntities.InsertAsync(entity);

        // Assert
        Assert.Equal(1, result);
    }

    #endregion
}
