using Nahmadov.DapperForge.Core.Builders;
using Nahmadov.DapperForge.Core.Common;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.Core.Mapping;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;
using Xunit;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

/// <summary>
/// Tests for Enum mapping: int storage, string storage, nullable enums, flags enums
/// </summary>
public class EnumMappingTests
{
    #region Enum Definitions

    public enum Status
    {
        Pending = 0,
        Active = 1,
        Inactive = 2,
        Deleted = 3
    }

    public enum Priority
    {
        Low = 1,
        Medium = 2,
        High = 3,
        Critical = 4
    }

    [Flags]
    public enum Permissions
    {
        None = 0,
        Read = 1,
        Write = 2,
        Delete = 4,
        Admin = 8,
        All = Read | Write | Delete | Admin
    }

    public enum Color
    {
        Red,
        Green,
        Blue,
        Yellow,
        Black,
        White
    }

    #endregion

    #region Test Models

    public class TaskEntity
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public Status Status { get; set; }
        public Priority Priority { get; set; }
        public Status? OptionalStatus { get; set; }
    }

    public class UserEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public Permissions Permissions { get; set; }
    }

    public class ProductEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public Color Color { get; set; }
        public Color? OptionalColor { get; set; }
    }

    public class TestContext : DapperDbContext
    {
        public DapperSet<TaskEntity> Tasks => Set<TaskEntity>();
        public DapperSet<UserEntity> Users => Set<UserEntity>();
        public DapperSet<ProductEntity> Products => Set<ProductEntity>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TaskEntity>(b =>
            {
                b.ToTable("Tasks");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<UserEntity>(b =>
            {
                b.ToTable("Users");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<ProductEntity>(b =>
            {
                b.ToTable("Products");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }

    #region Basic Enum Insert/Update Tests

    [Fact]
    public async Task InsertAsync_WithEnumValue_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Test Task",
            Status = Status.Active,
            Priority = Priority.High
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Tasks.InsertAsync(task);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task InsertAsync_WithDefaultEnumValue_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Test Task",
            Status = Status.Pending, // Default value (0)
            Priority = Priority.Low
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Tasks.InsertAsync(task);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task UpdateAsync_ChangesEnumValue_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Test Task",
            Status = Status.Active,
            Priority = Priority.Critical
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Tasks.UpdateAsync(task);

        // Assert
        Assert.Equal(1, result);
    }

    #endregion

    #region Enum Query Tests

    [Fact]
    public async Task Where_EnumEquals_FindsMatch()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Active Task", Status = Status.Active, Priority = Priority.High },
            new TaskEntity { Id = 2, Title = "Pending Task", Status = Status.Pending, Priority = Priority.Low }
        };
        conn.SetupQuery(new[] { tasks[0] });

        // Act
        var result = await ctx.Tasks.Query().Where(t => t.Status == Status.Active).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Equal(Status.Active, result.First().Status);
    }

    [Fact]
    public async Task Where_EnumNotEquals_FiltersCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Active Task", Status = Status.Active, Priority = Priority.High },
            new TaskEntity { Id = 2, Title = "Inactive Task", Status = Status.Inactive, Priority = Priority.Low }
        };
        conn.SetupQuery(tasks.Where(t => t.Status != Status.Deleted).ToArray());

        // Act
        var result = await ctx.Tasks.Query().Where(t => t.Status != Status.Deleted).ToListAsync();

        // Assert
        Assert.Equal(2, result.Count());
        Assert.All(result, t => Assert.NotEqual(Status.Deleted, t.Status));
    }

    [Fact]
    public async Task Where_MultipleEnumConditions_FiltersCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Critical Active", Status = Status.Active, Priority = Priority.Critical }
        };
        conn.SetupQuery(tasks);

        // Act
        var result = await ctx.Tasks.Query()
            .Where(t => t.Status == Status.Active && t.Priority == Priority.Critical)
            .ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Equal(Status.Active, result.First().Status);
        Assert.Equal(Priority.Critical, result.First().Priority);
    }

    [Fact]
    public async Task OrderBy_EnumValue_SortsByUnderlyingInt()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Task1", Status = Status.Active, Priority = Priority.Critical },
            new TaskEntity { Id = 2, Title = "Task2", Status = Status.Active, Priority = Priority.Low },
            new TaskEntity { Id = 3, Title = "Task3", Status = Status.Active, Priority = Priority.High }
        };
        var sortedTasks = tasks.OrderBy(t => t.Priority).ToArray();
        conn.SetupQuery(sortedTasks);

        // Act
        var result = (await ctx.Tasks.Query().OrderBy(t => t.Priority).ToListAsync()).ToList();

        // Assert
        Assert.Equal(3, result.Count);
        Assert.Equal(Priority.Low, result[0].Priority);
        Assert.Equal(Priority.High, result[1].Priority);
        Assert.Equal(Priority.Critical, result[2].Priority);
    }

    #endregion

    #region Nullable Enum Tests

    [Fact]
    public async Task InsertAsync_WithNullableEnum_HandlesNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Test Task",
            Status = Status.Active,
            Priority = Priority.High,
            OptionalStatus = null
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Tasks.InsertAsync(task);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task InsertAsync_WithNullableEnumValue_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Test Task",
            Status = Status.Active,
            Priority = Priority.High,
            OptionalStatus = Status.Inactive
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Tasks.InsertAsync(task);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task Where_NullableEnum_IsNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "No Optional", Status = Status.Active, Priority = Priority.High, OptionalStatus = null }
        };
        conn.SetupQuery(tasks);

        // Act
        var result = await ctx.Tasks.Query().Where(t => t.OptionalStatus == null).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Null(result.First().OptionalStatus);
    }

    [Fact]
    public async Task Where_NullableEnum_HasValue()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "With Optional", Status = Status.Active, Priority = Priority.High, OptionalStatus = Status.Deleted }
        };
        conn.SetupQuery(tasks);

        // Act
        var result = await ctx.Tasks.Query().Where(t => t.OptionalStatus == Status.Deleted).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Equal(Status.Deleted, result.First().OptionalStatus);
    }

    [Fact]
    public async Task Where_NullableEnum_NotNull()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "With Value", Status = Status.Active, Priority = Priority.High, OptionalStatus = Status.Active }
        };
        conn.SetupQuery(tasks);

        // Act
        var result = await ctx.Tasks.Query().Where(t => t.OptionalStatus != null).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.NotNull(result.First().OptionalStatus);
    }

    #endregion

    #region Flags Enum Tests

    [Fact]
    public async Task InsertAsync_WithFlagsEnum_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var user = new UserEntity
        {
            Id = 1,
            Name = "Admin User",
            Permissions = Permissions.Read | Permissions.Write | Permissions.Delete
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Users.InsertAsync(user);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task InsertAsync_WithAllFlags_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var user = new UserEntity
        {
            Id = 1,
            Name = "Super Admin",
            Permissions = Permissions.All
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Users.InsertAsync(user);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task InsertAsync_WithNoFlags_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var user = new UserEntity
        {
            Id = 1,
            Name = "Guest",
            Permissions = Permissions.None
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Users.InsertAsync(user);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task Query_WithFlagsEnum_FindsMatch()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var users = new[]
        {
            new UserEntity { Id = 1, Name = "User1", Permissions = Permissions.Read | Permissions.Write }
        };
        conn.SetupQuery(users);

        // Act
        var combinedPermissions = Permissions.Read | Permissions.Write;
        var result = await ctx.Users.Query().Where(u => u.Permissions == combinedPermissions).ToListAsync();

        // Assert
        Assert.Single(result);
    }

    #endregion

    #region Enum Zero Value Tests

    [Fact]
    public async Task InsertAsync_EnumZeroValue_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Pending Task",
            Status = Status.Pending, // 0
            Priority = Priority.Low
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Tasks.InsertAsync(task);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task Where_EnumZeroValue_FindsMatch()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Pending", Status = Status.Pending, Priority = Priority.Low }
        };
        conn.SetupQuery(tasks);

        // Act
        var result = await ctx.Tasks.Query().Where(t => t.Status == Status.Pending).ToListAsync();

        // Assert
        Assert.Single(result);
        Assert.Equal(Status.Pending, result.First().Status);
    }

    [Fact]
    public async Task InsertAsync_ColorEnumDefaultValue_IsRed()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var product = new ProductEntity
        {
            Id = 1,
            Name = "Product",
            Color = default(Color) // Should be Color.Red (0)
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Products.InsertAsync(product);

        // Assert
        Assert.Equal(1, result);
        Assert.Equal(Color.Red, product.Color);
    }

    #endregion

    #region Enum Boundary Value Tests

    [Fact]
    public async Task InsertAsync_EnumMaxValue_Succeeds()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Deleted Task",
            Status = Status.Deleted, // Highest value
            Priority = Priority.Critical // Highest value
        };
        conn.SetupExecute(1);

        // Act
        var result = await ctx.Tasks.InsertAsync(task);

        // Assert
        Assert.Equal(1, result);
    }

    [Fact]
    public async Task Where_AllEnumValues_FindsAll()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Pending", Status = Status.Pending, Priority = Priority.Low },
            new TaskEntity { Id = 2, Title = "Active", Status = Status.Active, Priority = Priority.Medium },
            new TaskEntity { Id = 3, Title = "Inactive", Status = Status.Inactive, Priority = Priority.High },
            new TaskEntity { Id = 4, Title = "Deleted", Status = Status.Deleted, Priority = Priority.Critical }
        };
        conn.SetupQuery(tasks);

        // Act - Query for all possible status values
        var result = await ctx.Tasks.Query().ToListAsync();

        // Assert
        Assert.Equal(4, result.Count());
        Assert.Contains(result, t => t.Status == Status.Pending);
        Assert.Contains(result, t => t.Status == Status.Active);
        Assert.Contains(result, t => t.Status == Status.Inactive);
        Assert.Contains(result, t => t.Status == Status.Deleted);
    }

    #endregion

    #region Enum in Complex Queries

    [Fact]
    public async Task Where_EnumWithStringCondition_CombinesCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Important Task", Status = Status.Active, Priority = Priority.High }
        };
        conn.SetupQuery(tasks);

        // Act
        var result = await ctx.Tasks.Query()
            .Where(t => t.Status == Status.Active && t.Title.Contains("Important"))
            .ToListAsync();

        // Assert
        Assert.Single(result);
    }

    [Fact]
    public async Task OrderBy_ThenBy_WithEnums_SortsCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var tasks = new[]
        {
            new TaskEntity { Id = 1, Title = "Task1", Status = Status.Active, Priority = Priority.High },
            new TaskEntity { Id = 2, Title = "Task2", Status = Status.Active, Priority = Priority.Low },
            new TaskEntity { Id = 3, Title = "Task3", Status = Status.Pending, Priority = Priority.High }
        };
        var sortedTasks = tasks.OrderBy(t => t.Status).ThenBy(t => t.Priority).ToArray();
        conn.SetupQuery(sortedTasks);

        // Act
        var result = (await ctx.Tasks.Query()
            .OrderBy(t => t.Status)
            .ThenBy(t => t.Priority)
            .ToListAsync()).ToList();

        // Assert
        Assert.Equal(3, result.Count);
        // First: Pending (0), High (3)
        Assert.Equal(Status.Pending, result[0].Status);
        // Next two: Active (1), Low (1) then High (3)
        Assert.Equal(Status.Active, result[1].Status);
        Assert.Equal(Priority.Low, result[1].Priority);
        Assert.Equal(Status.Active, result[2].Status);
        Assert.Equal(Priority.High, result[2].Priority);
    }

    #endregion

    #region Find by Enum Tests

    [Fact]
    public async Task FindAsync_WithEnumInEntity_ReturnsCorrectEntity()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var task = new TaskEntity
        {
            Id = 1,
            Title = "Test Task",
            Status = Status.Active,
            Priority = Priority.Critical
        };
        conn.SetupQuery(new[] { task });

        // Act
        var result = await ctx.Tasks.FindAsync(1);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(Status.Active, result.Status);
        Assert.Equal(Priority.Critical, result.Priority);
    }

    #endregion
}
