using Nahmadov.DapperForge.Core.Modeling.Builders;
using Nahmadov.DapperForge.Core.Context.Options;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

public partial class EnumMappingTests
{
    #region Enum Definitions

    public enum Status
    {
        Pending = 0,
        Active = 1,
        Inactive = 2,
        Deleted = 3
    }

    public enum Priority
    {
        Low = 1,
        Medium = 2,
        High = 3,
        Critical = 4
    }

    [Flags]
    public enum Permissions
    {
        None = 0,
        Read = 1,
        Write = 2,
        Delete = 4,
        Admin = 8,
        All = Read | Write | Delete | Admin
    }

    public enum Color
    {
        Red,
        Green,
        Blue,
        Yellow,
        Black,
        White
    }

    #endregion

    #region Test Models

    public class TaskEntity
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public Status Status { get; set; }
        public Priority Priority { get; set; }
        public Status? OptionalStatus { get; set; }
    }

    public class UserEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public Permissions Permissions { get; set; }
    }

    public class ProductEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public Color Color { get; set; }
        public Color? OptionalColor { get; set; }
    }

    public class TestContext : DapperDbContext
    {
        public DapperSet<TaskEntity> Tasks => Set<TaskEntity>();
        public DapperSet<UserEntity> Users => Set<UserEntity>();
        public DapperSet<ProductEntity> Products => Set<ProductEntity>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TaskEntity>(b =>
            {
                b.ToTable("Tasks");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<UserEntity>(b =>
            {
                b.ToTable("Users");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<ProductEntity>(b =>
            {
                b.ToTable("Products");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }
}
