using Nahmadov.DapperForge.Core.Attributes;
using Nahmadov.DapperForge.Core.Builders;
using Nahmadov.DapperForge.Core.Common;
using Nahmadov.DapperForge.Core.Context;
using Nahmadov.DapperForge.Core.Mapping;
using Nahmadov.DapperForge.SqlServer;
using Nahmadov.DapperForge.UnitTests.Fakes;
using Xunit;

namespace Nahmadov.DapperForge.UnitTests.EdgeCases;

/// <summary>
/// Tests for large result sets: 10k+ rows, memory usage, identity cache behavior
/// </summary>
public class LargeDataSetTests
{
    #region Test Models

    public class LargeEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
    }

    public class ParentEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public List<ChildEntity> Children { get; set; } = new();
    }

    public class ChildEntity
    {
        public int Id { get; set; }
        [ForeignKey(nameof(Parent), typeof(ParentEntity), nameof(ParentEntity.Id))]
        public int ParentId { get; set; }
        public string Value { get; set; } = string.Empty;
        public ParentEntity? Parent { get; set; }
    }

    public class TestContext : DapperDbContext
    {
        public DapperSet<LargeEntity> LargeEntities => Set<LargeEntity>();
        public DapperSet<ParentEntity> Parents => Set<ParentEntity>();
        public DapperSet<ChildEntity> Children => Set<ChildEntity>();

        public TestContext(DapperDbContextOptions options) : base(options) { }

        protected override void OnModelCreating(DapperModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LargeEntity>(b =>
            {
                b.ToTable("LargeEntities");
                b.Property(e => e.Id).AutoGenerated(false);
            });

            modelBuilder.Entity<ParentEntity>(b =>
            {
                b.ToTable("Parents");
                b.Property(e => e.Id).AutoGenerated(false);
                // b.HasMany(p => p.Children)
                    // .WithForeignKey(c => c.ParentId);
            });

            modelBuilder.Entity<ChildEntity>(b =>
            {
                b.ToTable("Children");
                b.Property(e => e.Id).AutoGenerated(false);
            });
        }
    }

    #endregion

    private static (TestContext context, FakeDbConnection connection) CreateContext()
    {
        var connection = new FakeDbConnection();
        var options = new DapperDbContextOptions
        {
            ConnectionFactory = () => connection,
            Dialect = SqlServerDialect.Instance
        };

        return (new TestContext(options), connection);
    }

    #region Large Result Set Tests

    [Fact]
    public async Task ToListAsync_10kRows_ReturnsAllRows()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);
        conn.SetupQuery(largeDataSet);

        // Act
        var result = await ctx.LargeEntities.Query().ToListAsync();

        // Assert
        Assert.Equal(10_000, result.Count());
    }

    [Fact]
    public async Task ToListAsync_50kRows_HandlesLargeVolume()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(50_000);
        conn.SetupQuery(largeDataSet);

        // Act
        var result = await ctx.LargeEntities.Query().ToListAsync();

        // Assert
        Assert.Equal(50_000, result.Count());
    }

    [Fact]
    public async Task ToListAsync_100kRows_CompletesSuccessfully()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(100_000);
        conn.SetupQuery(largeDataSet);

        // Act
        var result = await ctx.LargeEntities.Query().ToListAsync();

        // Assert
        Assert.Equal(100_000, result.Count());
    }

    [Fact]
    public async Task Where_On10kRows_FiltersCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);
        // Only first 100 are active
        for (int i = 100; i < largeDataSet.Length; i++)
        {
            largeDataSet[i].IsActive = false;
        }
        conn.SetupQuery(largeDataSet.Where(e => e.IsActive).ToArray());

        // Act
        var result = await ctx.LargeEntities.Query().Where(e => e.IsActive).ToListAsync();

        // Assert
        Assert.Equal(100, result.Count());
        Assert.All(result, e => Assert.True(e.IsActive));
    }

    [Fact]
    public async Task OrderBy_On10kRows_MaintainsOrder()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);
        var orderedData = largeDataSet.OrderBy(e => e.Amount).ToArray();
        conn.SetupQuery(orderedData);

        // Act
        var result = (await ctx.LargeEntities.Query().OrderBy(e => e.Amount).ToListAsync()).ToList();

        // Assert
        Assert.Equal(10_000, result.Count);
        // Verify ascending order
        for (int i = 1; i < result.Count; i++)
        {
            Assert.True(result[i].Amount >= result[i - 1].Amount);
        }
    }

    [Fact]
    public async Task Distinct_On10kRowsWithDuplicates_RemovesDuplicates()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var dataSet = GenerateLargeDataSet(1_000);
        // Duplicate each row 10 times = 10k rows total
        var withDuplicates = dataSet.SelectMany(e => Enumerable.Repeat(e, 10)).ToArray();
        conn.SetupQuery(dataSet); // Return unique set

        // Act
        var result = await ctx.LargeEntities.Query().Distinct().ToListAsync();

        // Assert
        Assert.Equal(1_000, result.Count());
    }

    #endregion

    #region Pagination Tests

    [Fact]
    public async Task SkipTake_Pagination_Through10kRows()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);

        // Act - Paginate through data (100 rows per page)
        var allResults = new List<LargeEntity>();
        for (int page = 0; page < 100; page++)
        {
            var pageData = largeDataSet.Skip(page * 100).Take(100).ToArray();
            conn.SetupQuery(pageData);

            var pageResult = await ctx.LargeEntities.Query().Skip(page * 100).Take(100).ToListAsync();
            allResults.AddRange(pageResult);
        }

        // Assert
        Assert.Equal(10_000, allResults.Count);
    }

    [Fact]
    public async Task Take_First100_From50kRows()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(50_000);
        conn.SetupQuery(largeDataSet.Take(100).ToArray());

        // Act
        var result = await ctx.LargeEntities.Query().Take(100).ToListAsync();

        // Assert
        Assert.Equal(100, result.Count());
    }

    [Fact]
    public async Task Skip_Last100_From10kRows()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);
        conn.SetupQuery(largeDataSet.Skip(9_900).ToArray());

        // Act
        var result = await ctx.LargeEntities.Query().Skip(9_900).ToListAsync();

        // Assert
        Assert.Equal(100, result.Count());
    }

    #endregion

    #region Identity Cache Tests with Large Data

    [Fact]
    public async Task Include_LargeResultSet_WithinCacheLimit()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        // Create 100 parents with 10 children each = 1000 total entities (within 10k cache limit)
        var parents = Enumerable.Range(1, 100)
            .Select(i => new ParentEntity { Id = i, Name = $"Parent{i}" })
            .ToArray();

        var children = parents.SelectMany(p =>
            Enumerable.Range(1, 10).Select(j => new ChildEntity
            {
                Id = p.Id * 100 + j,
                ParentId = p.Id,
                Value = $"Child{j}"
            })
        ).ToArray();

        conn.SetupQuery(parents);
        conn.SetupSplitQuery(children);

        // Act
        var result = await ctx.Parents.Query()
            .Include(p => p.Children)
            .AsSplitQuery()
            .ToListAsync();

        // Assert
        Assert.Equal(100, result.Count());
        Assert.All(result, p => Assert.Equal(10, p.Children.Count));
    }

    [Fact]
    public async Task Include_ExceedsCacheLimit_StillWorksCorrectly()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        // Create 2000 parents with 10 children each = 22k total entities (exceeds 10k cache limit)
        var parents = Enumerable.Range(1, 2000)
            .Select(i => new ParentEntity { Id = i, Name = $"Parent{i}" })
            .ToArray();

        var children = parents.SelectMany(p =>
            Enumerable.Range(1, 10).Select(j => new ChildEntity
            {
                Id = p.Id * 100 + j,
                ParentId = p.Id,
                Value = $"Child{j}"
            })
        ).ToArray();

        conn.SetupQuery(parents);
        conn.SetupSplitQuery(children);

        // Act
        var result = await ctx.Parents.Query()
            .Include(p => p.Children)
            .AsSplitQuery()
            .ToListAsync();

        // Assert
        Assert.Equal(2000, result.Count());
        // Children should still be mapped correctly despite cache evictions
        Assert.All(result, p => Assert.Equal(10, p.Children.Count));
    }

    [Fact]
    public async Task AsNoIdentityResolution_LargeDataSet_SkipsCaching()
    {
        // Arrange
        var (ctx, conn) = CreateContext();

        var parents = Enumerable.Range(1, 1000)
            .Select(i => new ParentEntity { Id = i, Name = $"Parent{i}" })
            .ToArray();

        var children = parents.SelectMany(p =>
            Enumerable.Range(1, 5).Select(j => new ChildEntity
            {
                Id = p.Id * 100 + j,
                ParentId = p.Id,
                Value = $"Child{j}"
            })
        ).ToArray();

        conn.SetupQuery(parents);
        conn.SetupSplitQuery(children);

        // Act
        var result = await ctx.Parents.Query()
            .Include(p => p.Children)
            .AsNoIdentityResolution()
            .AsSplitQuery()
            .ToListAsync();

        // Assert
        Assert.Equal(1000, result.Count());
        Assert.All(result, p => Assert.Equal(5, p.Children.Count));
    }

    #endregion

    #region Performance and Memory Tests

    [Fact]
    public async Task MultipleQueries_On10kRows_NoMemoryLeak()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);

        // Act - Execute multiple queries to ensure no memory accumulation
        for (int i = 0; i < 10; i++)
        {
            conn.SetupQuery(largeDataSet);
            var result = await ctx.LargeEntities.Query().ToListAsync();
            Assert.Equal(10_000, result.Count());
        }

        // Assert - Completes without memory issues
        Assert.True(true);
    }

    [Fact]
    public async Task CountAsync_On100kRows_ReturnsCorrectCount()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        conn.SetupScalar(100_000L);

        // Act
        var count = await ctx.LargeEntities.CountAsync(e => true);

        // Assert
        Assert.Equal(100_000, count);
    }

    [Fact]
    public async Task AnyAsync_On10kRows_ReturnsTrue()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);
        conn.SetupQuery(largeDataSet.Take(1).ToArray());

        // Act
        var hasAny = await ctx.LargeEntities.AnyAsync(e => true);

        // Assert
        Assert.True(hasAny);
    }

    [Fact]
    public async Task FirstAsync_On10kRows_ReturnsFirst()
    {
        // Arrange
        var (ctx, conn) = CreateContext();
        var largeDataSet = GenerateLargeDataSet(10_000);
        conn.SetupQuery(new[] { largeDataSet[0] });

        // Act
        var first = await ctx.LargeEntities.FirstAsync(e => true);

        // Assert
        Assert.NotNull(first);
        Assert.Equal(largeDataSet[0].Id, first.Id);
    }

    #endregion

    #region Helper Methods

    private static LargeEntity[] GenerateLargeDataSet(int count)
    {
        var entities = new LargeEntity[count];
        var random = new Random(42); // Seed for reproducibility

        for (int i = 0; i < count; i++)
        {
            entities[i] = new LargeEntity
            {
                Id = i + 1,
                Name = $"Entity_{i + 1}",
                Description = $"Description for entity {i + 1} with some additional text to simulate real data",
                CreatedAt = DateTime.Now.AddDays(-random.Next(0, 365)),
                Amount = (decimal)(random.NextDouble() * 10000),
                IsActive = i < 100 // First 100 are active by default
            };
        }

        return entities;
    }

    #endregion
}
