using Nahmadov.DapperForge.Core.Modeling.Mapping;
using Nahmadov.DapperForge.Core.Modeling.Schema;

namespace Nahmadov.DapperForge.Core.Modeling.Builders;
/// <summary>
/// Fluent builder for configuring an individual property mapping.
/// </summary>
public class PropertyBuilder(PropertyConfig property)
{
    private readonly PropertyConfig _property = property;

    /// <summary>
    /// Overrides the column name for the property.
    /// </summary>
    /// <param name="columnName">Database column name.</param>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder HasColumnName(string columnName)
    {
        _property.SetColumnName(columnName);
        return this;
    }

    /// <summary>
    /// Marks the property as required.
    /// </summary>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder IsRequired(bool required = true)
    {
        _property.SetRequired(required);
        return this;
    }

    /// <summary>
    /// Marks the property as optional, overriding any [Required] attribute.
    /// </summary>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder IsOptional()
    {
        _property.SetRequired(false);
        return this;
    }

    /// <summary>
    /// Sets the maximum allowed length for string values.
    /// </summary>
    /// <param name="maxLength">Maximum character length.</param>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder HasMaxLength(int maxLength)
    {
        _property.SetMaxLength(maxLength);
        return this;
    }

    /// <summary>
    /// Assigns a database sequence to generate values for the property.
    /// </summary>
    /// <param name="sequenceName">Sequence name.</param>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder HasSequence(string sequenceName)
    {
        if (string.IsNullOrWhiteSpace(sequenceName))
            throw new ArgumentException("Sequence name cannot be empty.", nameof(sequenceName));

        _property.SetSequence(sequenceName);
        return this;
    }

    /// <summary>
    /// Marks the property as read-only, excluding it from updates.
    /// </summary>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder IsReadOnly(bool readOnly = true)
    {
        _property.SetReadOnly(readOnly);
        return this;
    }

    /// <summary>
    /// Configures whether the property value is auto-generated by the database.
    /// </summary>
    /// <param name="autoGenerated">True to mark as generated; false to include in inserts.</param>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder AutoGenerated(bool? autoGenerated = true)
    {
        _property.SetAutoGenerated(autoGenerated);
        return this;
    }

    /// <summary>
    /// Sets the explicit SQL column type, overriding automatic CLR-type inference.
    /// </summary>
    /// <param name="type">The dialect-agnostic SQL column type.</param>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder HasColumnType(SqlColumnType type)
    {
        _property.SetColumnType(type, default);
        return this;
    }

    /// <summary>
    /// Sets the explicit SQL column type with a length facet (for string/binary types).
    /// </summary>
    /// <param name="type">The dialect-agnostic SQL column type.</param>
    /// <param name="length">Maximum length; use <see cref="ColumnTypeFacets.Max"/> (-1) for the MAX/unbounded variant.</param>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder HasColumnType(SqlColumnType type, int length)
    {
        _property.SetColumnType(type, new ColumnTypeFacets(Length: length));
        return this;
    }

    /// <summary>
    /// Sets the explicit SQL column type with precision and scale facets (for decimal/money types).
    /// </summary>
    /// <param name="type">The dialect-agnostic SQL column type.</param>
    /// <param name="precision">Total number of digits.</param>
    /// <param name="scale">Number of digits to the right of the decimal point.</param>
    /// <returns>The current builder for chaining.</returns>
    public PropertyBuilder HasColumnType(SqlColumnType type, int precision, int scale)
    {
        _property.SetColumnType(type, new ColumnTypeFacets(Precision: precision, Scale: scale));
        return this;
    }
}


