using Nahmadov.DapperForge.Core.Modeling.Schema;

namespace Nahmadov.DapperForge.Core.Modeling.Mapping;
/// <summary>
/// Stores fluent configuration options for a single entity property.
/// </summary>
public class PropertyConfig(string propertyName)
{
    public string PropertyName { get; } = propertyName;
    public string? ColumnName { get; private set; }
    public bool? IsRequired { get; private set; }
    public bool? IsReadOnly { get; private set; }
    public int? MaxLength { get; private set; }
    public string? SequenceName { get; private set; }
    public bool? IsAutoGenerated { get; private set; }

    /// <summary>Explicitly configured SQL column type, if any. Overrides inference.</summary>
    public SqlColumnType? ColumnType { get; private set; }

    /// <summary>Facets (length/precision/scale) accompanying <see cref="ColumnType"/>.</summary>
    public ColumnTypeFacets ColumnTypeFacets { get; private set; }

    /// <summary>
    /// Sets the database column name for the property.
    /// </summary>
    public void SetColumnName(string columnName) => ColumnName = columnName;

    /// <summary>
    /// Marks the property as required.
    /// </summary>
    public void SetRequired(bool? required) => IsRequired = required;

    /// <summary>
    /// Marks the property as read-only.
    /// </summary>
    public void SetReadOnly(bool? readOnly) => IsReadOnly = readOnly;

    /// <summary>
    /// Sets the maximum length constraint for the property.
    /// </summary>
    public void SetMaxLength(int? length) => MaxLength = length;

    /// <summary>
    /// Assigns the database sequence used to generate values.
    /// </summary>
    public void SetSequence(string? sequenceName) => SequenceName = sequenceName;

    /// <summary>
    /// Sets whether the property value is auto-generated by the database.
    /// </summary>
    /// <param name="autoGenerated">True to mark as generated, false to disable generation.</param>
    public void SetAutoGenerated(bool? autoGenerated) => IsAutoGenerated = autoGenerated;

    /// <summary>
    /// Sets the explicit SQL column type and its facets, overriding type inference.
    /// </summary>
    public void SetColumnType(SqlColumnType type, ColumnTypeFacets facets)
    {
        ColumnType = type;
        ColumnTypeFacets = facets;
    }
}

